### ISSUE TITLE
Write mail to contact meetups with info about the event and C4P

### ISSUE THREAD

**Issue by DavidHernandez** [VLCTechHub/VLCTechFest2018#17]

**Comment by Pardiez** [comment]
[ ] Pedir logo
[ ] Pedir diversidad en las propuestas

**Comment by DavidHernandez** [comment]
https://docs.google.com/document/d/1t5TsnXtwFl2-XRblHlTKL_pFU-NXnjtNQBs0FeAcYVE/edit
