### ISSUE TITLE
Typo in the title

### ISSUE THREAD

**Issue by jguitar** [VLCTechHub/VLCTechFest2018#25]
I was lurking the new page and I though that "Se parte del VLCTechFest 2018" was a WIP. Something like "Partimos del diseño de VLCTechFest 2017" or something similar.
But, are you meaning "Sé parte...", right? In that case there is a typo.

**Comment by esebastian** [comment]
I guess it's the second one @jguitar, doesn't it @DavidHernandez ?

If that's the case instead of "Sé parte del VLCTEchFest 2018", we could also use something like "Forma parte del VLCTechFest 2018" if it makes it clearer.

**Comment by hell03610** [comment]
Thanks for lurking, the official announcement is quite close! We decided to just say "VLCTechFest 2018" - We might change it to "forma parte..."

**Comment by jguitar** [comment]
You're welcome
