### ISSUE TITLE
The logos of the communities don't resize properly in single column layout

### ISSUE THREAD

**Issue by esebastian** [VLCTechHub/VLCTechFest2018#30]
When the small devices `min-width` (768px) is reached and the site changes to the one column layout, the logos of the communities are rendered in different sizes until the width of all of them becomes the same:

![fireshot capture 052 - vlctechfest 2018 - http___localhost_8000_](https://user-images.githubusercontent.com/577074/38954929-6a9d9a1e-4353-11e8-9118-11f78b8a30ed.png)

**Comment by esebastian** [comment]
As the smaller images get pulled to the left and don't start resizing until the width of the container is smaller than their own width, it looks like the preferred solution would be to use bigger images, with a minimum with of 768px.

**Comment by Pardiez** [comment]
They have simply been aligned centrally. 
We don't have images of such quality from many of the communities.
