### ISSUE TITLE
The logos of the communities don't get distributed evenly on small devices

### ISSUE THREAD

**Issue by esebastian** [VLCTechHub/VLCTechFest2018#31]
When the small devices breakpoint is reached the images are resized accordingly but the original distribution in threes is lost on the second row:

![fireshot capture 053 - vlctechfest 2018 - http___vlctechfest org_](https://user-images.githubusercontent.com/577074/38956493-0c1d0f24-4358-11e8-869a-5bcff348420f.png)

**Comment by Pardiez** [comment]
fixed #39
