### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by DavidHernandez** [VLCTechHub/VLCTechFest2018#48]
- Cuanto cuesta la entrada?
- Hay que registrarse? (Que pasa si se llena una sala?)
- Hay comida incluida? -> No, habra un paron de dos horas para comer. Las Naves tiene cafeteria, ademas, el centro comercial Acqua esta bastante cerca. Ademas, habra dispensadores de agua por lo que si tienes cantimplora, traela para reducir el derroche de plastico.
- Se van a grabar las sesiones?

**Comment by hell03610** [comment]
Done
